//======================================================
// Source code generated by jvider v1.8.1 UNREGISTERED version.
// http://www.jvider.com/
//======================================================
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JPanel;
import javax.swing.BorderFactory;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JButton;
/**
 * @author  Administrator
 * @created December 12, 2019
 */
public class alterarCateogriaNome extends JFrame 
{
static alterarCateogriaNome thealterarCateogriaNome;

JPanel pnPanel0;
JLabel lbLabel0;
JTextField tfText;
JButton btBut0;
/**
 */
public static void main( String args[] ) 
{
   try 
   {
      UIManager.setLookAndFeel("javax.swing.plaf.mac.MacLookAndFeel");
   }
   catch ( ClassNotFoundException e ) 
   {
   }
   catch ( InstantiationException e ) 
   {
   }
   catch ( IllegalAccessException e ) 
   {
   }
   catch ( UnsupportedLookAndFeelException e ) 
   {
   }
   thealterarCateogriaNome = new alterarCateogriaNome();
} 

/**
 */
public alterarCateogriaNome() 
{
   super( "TITLE" );

   pnPanel0 = new JPanel();
   GridBagLayout gbPanel0 = new GridBagLayout();
   GridBagConstraints gbcPanel0 = new GridBagConstraints();
   pnPanel0.setLayout( gbPanel0 );

   lbLabel0 = new JLabel( "Alterar Categoria"  );
   gbcPanel0.gridx = 3;
   gbcPanel0.gridy = 0;
   gbcPanel0.gridwidth = 1;
   gbcPanel0.gridheight = 1;
   gbcPanel0.fill = GridBagConstraints.NONE;
   gbcPanel0.weightx = 0;
   gbcPanel0.weighty = 0;
   gbcPanel0.anchor = GridBagConstraints.NORTH;
   gbcPanel0.insets = new Insets( 5,15,5,15 );
   gbPanel0.setConstraints( lbLabel0, gbcPanel0 );
   pnPanel0.add( lbLabel0 );

   tfText = new JTextField( );
   gbcPanel0.gridx = 3;
   gbcPanel0.gridy = 2;
   gbcPanel0.gridwidth = 1;
   gbcPanel0.gridheight = 2;
   gbcPanel0.fill = GridBagConstraints.BOTH;
   gbcPanel0.weightx = 1;
   gbcPanel0.weighty = 0;
   gbcPanel0.anchor = GridBagConstraints.NORTH;
   gbcPanel0.insets = new Insets( 0,15,0,15 );
   gbPanel0.setConstraints( tfText, gbcPanel0 );
   pnPanel0.add( tfText );

   btBut0 = new JButton( "Alterar"  );
   gbcPanel0.gridx = 3;
   gbcPanel0.gridy = 6;
   gbcPanel0.gridwidth = 1;
   gbcPanel0.gridheight = 1;
   gbcPanel0.fill = GridBagConstraints.NONE;
   gbcPanel0.weightx = 0;
   gbcPanel0.weighty = 0;
   gbcPanel0.anchor = GridBagConstraints.CENTER;
   gbcPanel0.insets = new Insets( 0,15,5,15 );
   gbPanel0.setConstraints( btBut0, gbcPanel0 );
   pnPanel0.add( btBut0 );

   setDefaultCloseOperation( EXIT_ON_CLOSE );

   setContentPane( pnPanel0 );
   pack();
   setVisible( true );
} 
} 
