//======================================================
// Source code generated by jvider v1.8.1 UNREGISTERED version.
// http://www.jvider.com/
//======================================================
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JPanel;
import javax.swing.BorderFactory;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JTextField;
import javax.swing.JTextArea;
import javax.swing.JComboBox;
import javax.swing.JButton;
/**
 * @author  Administrator
 * @created December 12, 2019
 */
public class criarPlaylist extends JFrame 
{
static criarPlaylist thecriarPlaylist;

JPanel pnCriarPlaylist;
JTextField tfNome;
JTextArea taDescricao;
JComboBox cmbCombo;
JButton btCancel;
JButton btConfirm;
JTextField tfText1;
/**
 */
public static void main( String args[] ) 
{
   try 
   {
      UIManager.setLookAndFeel("javax.swing.plaf.mac.MacLookAndFeel");
   }
   catch ( ClassNotFoundException e ) 
   {
   }
   catch ( InstantiationException e ) 
   {
   }
   catch ( IllegalAccessException e ) 
   {
   }
   catch ( UnsupportedLookAndFeelException e ) 
   {
   }
   thecriarPlaylist = new criarPlaylist();
} 

/**
 */
public criarPlaylist() 
{
   super( "TITLE" );

   pnCriarPlaylist = new JPanel();
   GridBagLayout gbCriarPlaylist = new GridBagLayout();
   GridBagConstraints gbcCriarPlaylist = new GridBagConstraints();
   pnCriarPlaylist.setLayout( gbCriarPlaylist );

   tfNome = new JTextField( );
   gbcCriarPlaylist.gridx = 2;
   gbcCriarPlaylist.gridy = 1;
   gbcCriarPlaylist.gridwidth = 14;
   gbcCriarPlaylist.gridheight = 3;
   gbcCriarPlaylist.fill = GridBagConstraints.HORIZONTAL;
   gbcCriarPlaylist.weightx = 1;
   gbcCriarPlaylist.weighty = 0;
   gbcCriarPlaylist.anchor = GridBagConstraints.CENTER;
   gbcCriarPlaylist.insets = new Insets( 15,15,0,15 );
   gbCriarPlaylist.setConstraints( tfNome, gbcCriarPlaylist );
   pnCriarPlaylist.add( tfNome );

   taDescricao = new JTextArea(2,10);
   gbcCriarPlaylist.gridx = 2;
   gbcCriarPlaylist.gridy = 5;
   gbcCriarPlaylist.gridwidth = 14;
   gbcCriarPlaylist.gridheight = 6;
   gbcCriarPlaylist.fill = GridBagConstraints.BOTH;
   gbcCriarPlaylist.weightx = 1;
   gbcCriarPlaylist.weighty = 1;
   gbcCriarPlaylist.anchor = GridBagConstraints.NORTH;
   gbcCriarPlaylist.insets = new Insets( 15,15,15,15 );
   gbCriarPlaylist.setConstraints( taDescricao, gbcCriarPlaylist );
   pnCriarPlaylist.add( taDescricao );

   String []dataCombo = { "Chocolate", "Ice Cream", "Apple Pie" };
   cmbCombo = new JComboBox( dataCombo );
   gbcCriarPlaylist.gridx = 2;
   gbcCriarPlaylist.gridy = 12;
   gbcCriarPlaylist.gridwidth = 14;
   gbcCriarPlaylist.gridheight = 3;
   gbcCriarPlaylist.fill = GridBagConstraints.BOTH;
   gbcCriarPlaylist.weightx = 1;
   gbcCriarPlaylist.weighty = 0;
   gbcCriarPlaylist.anchor = GridBagConstraints.NORTH;
   gbcCriarPlaylist.insets = new Insets( 0,15,0,15 );
   gbCriarPlaylist.setConstraints( cmbCombo, gbcCriarPlaylist );
   pnCriarPlaylist.add( cmbCombo );

   btCancel = new JButton( "Cancel"  );
   gbcCriarPlaylist.gridx = 2;
   gbcCriarPlaylist.gridy = 16;
   gbcCriarPlaylist.gridwidth = 6;
   gbcCriarPlaylist.gridheight = 3;
   gbcCriarPlaylist.fill = GridBagConstraints.NONE;
   gbcCriarPlaylist.weightx = 0;
   gbcCriarPlaylist.weighty = 0;
   gbcCriarPlaylist.anchor = GridBagConstraints.WEST;
   gbcCriarPlaylist.insets = new Insets( 0,15,15,0 );
   gbCriarPlaylist.setConstraints( btCancel, gbcCriarPlaylist );
   pnCriarPlaylist.add( btCancel );

   btConfirm = new JButton( "Confirm"  );
   gbcCriarPlaylist.gridx = 10;
   gbcCriarPlaylist.gridy = 16;
   gbcCriarPlaylist.gridwidth = 6;
   gbcCriarPlaylist.gridheight = 3;
   gbcCriarPlaylist.fill = GridBagConstraints.NONE;
   gbcCriarPlaylist.weightx = 0;
   gbcCriarPlaylist.weighty = 0;
   gbcCriarPlaylist.anchor = GridBagConstraints.EAST;
   gbcCriarPlaylist.insets = new Insets( 0,0,15,15 );
   gbCriarPlaylist.setConstraints( btConfirm, gbcCriarPlaylist );
   pnCriarPlaylist.add( btConfirm );

   tfText1 = new JTextField( );
   gbcCriarPlaylist.gridx = 2;
   gbcCriarPlaylist.gridy = 15;
   gbcCriarPlaylist.gridwidth = 14;
   gbcCriarPlaylist.gridheight = 1;
   gbcCriarPlaylist.fill = GridBagConstraints.BOTH;
   gbcCriarPlaylist.weightx = 1;
   gbcCriarPlaylist.weighty = 0;
   gbcCriarPlaylist.anchor = GridBagConstraints.CENTER;
   gbcCriarPlaylist.insets = new Insets( 15,15,15,15 );
   gbCriarPlaylist.setConstraints( tfText1, gbcCriarPlaylist );
   pnCriarPlaylist.add( tfText1 );

   setDefaultCloseOperation( EXIT_ON_CLOSE );

   setContentPane( pnCriarPlaylist );
   pack();
   setVisible( true );
} 
} 
