//======================================================
// Source code generated by jvider v1.8.1 UNREGISTERED version.
// http://www.jvider.com/
//======================================================
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JPanel;
import javax.swing.BorderFactory;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JLabel;
/**
 * @author  Administrator
 * @created December 2, 2019
 */
public class dialogmessage extends JFrame 
{
static dialogmessage thedialogmessage;

JPanel pnPanel0;
JLabel lbMessage;
/**
 */
public static void main( String args[] ) 
{
   try 
   {
      UIManager.setLookAndFeel("javax.swing.plaf.mac.MacLookAndFeel");
   }
   catch ( ClassNotFoundException e ) 
   {
   }
   catch ( InstantiationException e ) 
   {
   }
   catch ( IllegalAccessException e ) 
   {
   }
   catch ( UnsupportedLookAndFeelException e ) 
   {
   }
   thedialogmessage = new dialogmessage();
} 

/**
 */
public dialogmessage() 
{
   super( "TITLE" );

   pnPanel0 = new JPanel();
   GridBagLayout gbPanel0 = new GridBagLayout();
   GridBagConstraints gbcPanel0 = new GridBagConstraints();
   pnPanel0.setLayout( gbPanel0 );

   lbMessage = new JLabel( "aaaaa"  );
   gbcPanel0.gridx = 5;
   gbcPanel0.gridy = 5;
   gbcPanel0.gridwidth = 1;
   gbcPanel0.gridheight = 1;
   gbcPanel0.fill = GridBagConstraints.NONE;
   gbcPanel0.weightx = 0;
   gbcPanel0.weighty = 0;
   gbcPanel0.anchor = GridBagConstraints.CENTER;
   gbPanel0.setConstraints( lbMessage, gbcPanel0 );
   pnPanel0.add( lbMessage );

   setDefaultCloseOperation( EXIT_ON_CLOSE );

   setContentPane( pnPanel0 );
   pack();
   setVisible( true );
} 
} 
