//======================================================
// Source code generated by jvider v1.8.1 UNREGISTERED version.
// http://www.jvider.com/
//======================================================
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JPanel;
import javax.swing.BorderFactory;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JButton;
/**
 * @author  Administrator
 * @created December 2, 2019
 */
public class login extends JFrame 
{
static login thelogin;

JPanel pnLoginPanel;
JLabel lbUsernameLabel;
JLabel lbPasswordLabel;
JTextField tfUsernameField;
JTextField tfPasswordField;
JButton btGuestLogin;
JButton btLoginButton;
JButton btForgotButton;
/**
 */
public static void main( String args[] ) 
{
   try 
   {
      UIManager.setLookAndFeel("javax.swing.plaf.mac.MacLookAndFeel");
   }
   catch ( ClassNotFoundException e ) 
   {
   }
   catch ( InstantiationException e ) 
   {
   }
   catch ( IllegalAccessException e ) 
   {
   }
   catch ( UnsupportedLookAndFeelException e ) 
   {
   }
   thelogin = new login();
} 

/**
 */
public login() 
{
   super( "TITLE" );

   pnLoginPanel = new JPanel();
   GridBagLayout gbLoginPanel = new GridBagLayout();
   GridBagConstraints gbcLoginPanel = new GridBagConstraints();
   pnLoginPanel.setLayout( gbLoginPanel );

   lbUsernameLabel = new JLabel( "username:"  );
   gbcLoginPanel.gridx = 4;
   gbcLoginPanel.gridy = 4;
   gbcLoginPanel.gridwidth = 8;
   gbcLoginPanel.gridheight = 3;
   gbcLoginPanel.fill = GridBagConstraints.NONE;
   gbcLoginPanel.weightx = 0;
   gbcLoginPanel.weighty = 0;
   gbcLoginPanel.anchor = GridBagConstraints.EAST;
   gbcLoginPanel.insets = new Insets( 5,20,0,0 );
   gbLoginPanel.setConstraints( lbUsernameLabel, gbcLoginPanel );
   pnLoginPanel.add( lbUsernameLabel );

   lbPasswordLabel = new JLabel( "password:"  );
   gbcLoginPanel.gridx = 4;
   gbcLoginPanel.gridy = 8;
   gbcLoginPanel.gridwidth = 8;
   gbcLoginPanel.gridheight = 3;
   gbcLoginPanel.fill = GridBagConstraints.NONE;
   gbcLoginPanel.weightx = 0;
   gbcLoginPanel.weighty = 0;
   gbcLoginPanel.anchor = GridBagConstraints.EAST;
   gbcLoginPanel.insets = new Insets( 0,20,0,0 );
   gbLoginPanel.setConstraints( lbPasswordLabel, gbcLoginPanel );
   pnLoginPanel.add( lbPasswordLabel );

   tfUsernameField = new JTextField( );
   gbcLoginPanel.gridx = 12;
   gbcLoginPanel.gridy = 4;
   gbcLoginPanel.gridwidth = 11;
   gbcLoginPanel.gridheight = 3;
   gbcLoginPanel.fill = GridBagConstraints.BOTH;
   gbcLoginPanel.weightx = 0;
   gbcLoginPanel.weighty = 0;
   gbcLoginPanel.anchor = GridBagConstraints.CENTER;
   gbcLoginPanel.insets = new Insets( 5,0,0,20 );
   gbLoginPanel.setConstraints( tfUsernameField, gbcLoginPanel );
   pnLoginPanel.add( tfUsernameField );

   tfPasswordField = new JTextField( );
   gbcLoginPanel.gridx = 12;
   gbcLoginPanel.gridy = 8;
   gbcLoginPanel.gridwidth = 11;
   gbcLoginPanel.gridheight = 3;
   gbcLoginPanel.fill = GridBagConstraints.BOTH;
   gbcLoginPanel.weightx = 0;
   gbcLoginPanel.weighty = 0;
   gbcLoginPanel.anchor = GridBagConstraints.CENTER;
   gbcLoginPanel.insets = new Insets( 0,0,5,20 );
   gbLoginPanel.setConstraints( tfPasswordField, gbcLoginPanel );
   pnLoginPanel.add( tfPasswordField );

   btGuestLogin = new JButton( "Login as Guest"  );
   gbcLoginPanel.gridx = 4;
   gbcLoginPanel.gridy = 12;
   gbcLoginPanel.gridwidth = 9;
   gbcLoginPanel.gridheight = 4;
   gbcLoginPanel.fill = GridBagConstraints.BOTH;
   gbcLoginPanel.weightx = 1;
   gbcLoginPanel.weighty = 0;
   gbcLoginPanel.anchor = GridBagConstraints.NORTH;
   gbcLoginPanel.insets = new Insets( 0,0,5,0 );
   gbLoginPanel.setConstraints( btGuestLogin, gbcLoginPanel );
   pnLoginPanel.add( btGuestLogin );

   btLoginButton = new JButton( "Login"  );
   gbcLoginPanel.gridx = 14;
   gbcLoginPanel.gridy = 12;
   gbcLoginPanel.gridwidth = 9;
   gbcLoginPanel.gridheight = 4;
   gbcLoginPanel.fill = GridBagConstraints.BOTH;
   gbcLoginPanel.weightx = 1;
   gbcLoginPanel.weighty = 0;
   gbcLoginPanel.anchor = GridBagConstraints.NORTH;
   gbcLoginPanel.insets = new Insets( 0,0,5,0 );
   gbLoginPanel.setConstraints( btLoginButton, gbcLoginPanel );
   pnLoginPanel.add( btLoginButton );

   btForgotButton = new JButton( "Forgot Password"  );
   gbcLoginPanel.gridx = 12;
   gbcLoginPanel.gridy = 17;
   gbcLoginPanel.gridwidth = 11;
   gbcLoginPanel.gridheight = 1;
   gbcLoginPanel.fill = GridBagConstraints.NONE;
   gbcLoginPanel.weightx = 0;
   gbcLoginPanel.weighty = 0;
   gbcLoginPanel.anchor = GridBagConstraints.CENTER;
   gbLoginPanel.setConstraints( btForgotButton, gbcLoginPanel );
   pnLoginPanel.add( btForgotButton );

   setDefaultCloseOperation( EXIT_ON_CLOSE );

   setContentPane( pnLoginPanel );
   pack();
   setVisible( true );
} 
} 
