//======================================================
// Source code generated by jvider v1.8.1 UNREGISTERED version.
// http://www.jvider.com/
//======================================================
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JPanel;
import javax.swing.BorderFactory;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
/**
 * @author  Administrator
 * @created December 5, 2019
 */
public class upload extends JFrame 
{
static upload theupload;

JPanel pnMainPanel;
JButton btFileButton;
JLabel lbFileNameLabel;
JLabel lbValidLabel;
JTextField tfName;
JTextField tfArtistas;
JTextField tfCategorias;
JTextField tfAlbum;
JButton btUploadButton;
/**
 */
public static void main( String args[] ) 
{
   try 
   {
      UIManager.setLookAndFeel("javax.swing.plaf.mac.MacLookAndFeel");
   }
   catch ( ClassNotFoundException e ) 
   {
   }
   catch ( InstantiationException e ) 
   {
   }
   catch ( IllegalAccessException e ) 
   {
   }
   catch ( UnsupportedLookAndFeelException e ) 
   {
   }
   theupload = new upload();
} 

/**
 */
public upload() 
{
   super( "TITLE" );

   pnMainPanel = new JPanel();
   GridBagLayout gbMainPanel = new GridBagLayout();
   GridBagConstraints gbcMainPanel = new GridBagConstraints();
   pnMainPanel.setLayout( gbMainPanel );

   btFileButton = new JButton( "Select File"  );
   gbcMainPanel.gridx = 1;
   gbcMainPanel.gridy = 1;
   gbcMainPanel.gridwidth = 1;
   gbcMainPanel.gridheight = 1;
   gbcMainPanel.fill = GridBagConstraints.NONE;
   gbcMainPanel.weightx = 1;
   gbcMainPanel.weighty = 1;
   gbcMainPanel.anchor = GridBagConstraints.WEST;
   gbMainPanel.setConstraints( btFileButton, gbcMainPanel );
   pnMainPanel.add( btFileButton );

   lbFileNameLabel = new JLabel( "FileName.mp3"  );
   gbcMainPanel.gridx = 3;
   gbcMainPanel.gridy = 1;
   gbcMainPanel.gridwidth = 1;
   gbcMainPanel.gridheight = 1;
   gbcMainPanel.fill = GridBagConstraints.NONE;
   gbcMainPanel.weightx = 1;
   gbcMainPanel.weighty = 1;
   gbcMainPanel.anchor = GridBagConstraints.WEST;
   gbMainPanel.setConstraints( lbFileNameLabel, gbcMainPanel );
   pnMainPanel.add( lbFileNameLabel );

   lbValidLabel = new JLabel( "File is invalidvalid!"  );
   gbcMainPanel.gridx = 6;
   gbcMainPanel.gridy = 1;
   gbcMainPanel.gridwidth = 1;
   gbcMainPanel.gridheight = 1;
   gbcMainPanel.fill = GridBagConstraints.NONE;
   gbcMainPanel.weightx = 1;
   gbcMainPanel.weighty = 1;
   gbcMainPanel.anchor = GridBagConstraints.EAST;
   gbcMainPanel.insets = new Insets( 0,0,0,5 );
   gbMainPanel.setConstraints( lbValidLabel, gbcMainPanel );
   pnMainPanel.add( lbValidLabel );

   tfName = new JTextField( );
   gbcMainPanel.gridx = 1;
   gbcMainPanel.gridy = 3;
   gbcMainPanel.gridwidth = 6;
   gbcMainPanel.gridheight = 3;
   gbcMainPanel.fill = GridBagConstraints.BOTH;
   gbcMainPanel.weightx = 1;
   gbcMainPanel.weighty = 0;
   gbcMainPanel.anchor = GridBagConstraints.CENTER;
   gbcMainPanel.insets = new Insets( 0,15,0,15 );
   gbMainPanel.setConstraints( tfName, gbcMainPanel );
   pnMainPanel.add( tfName );

   tfArtistas = new JTextField( );
   gbcMainPanel.gridx = 1;
   gbcMainPanel.gridy = 7;
   gbcMainPanel.gridwidth = 6;
   gbcMainPanel.gridheight = 3;
   gbcMainPanel.fill = GridBagConstraints.BOTH;
   gbcMainPanel.weightx = 1;
   gbcMainPanel.weighty = 0;
   gbcMainPanel.anchor = GridBagConstraints.CENTER;
   gbcMainPanel.insets = new Insets( 0,15,0,15 );
   gbMainPanel.setConstraints( tfArtistas, gbcMainPanel );
   pnMainPanel.add( tfArtistas );

   tfCategorias = new JTextField( );
   gbcMainPanel.gridx = 1;
   gbcMainPanel.gridy = 11;
   gbcMainPanel.gridwidth = 6;
   gbcMainPanel.gridheight = 3;
   gbcMainPanel.fill = GridBagConstraints.BOTH;
   gbcMainPanel.weightx = 1;
   gbcMainPanel.weighty = 0;
   gbcMainPanel.anchor = GridBagConstraints.CENTER;
   gbcMainPanel.insets = new Insets( 0,15,0,15 );
   gbMainPanel.setConstraints( tfCategorias, gbcMainPanel );
   pnMainPanel.add( tfCategorias );

   tfAlbum = new JTextField( );
   gbcMainPanel.gridx = 1;
   gbcMainPanel.gridy = 15;
   gbcMainPanel.gridwidth = 6;
   gbcMainPanel.gridheight = 3;
   gbcMainPanel.fill = GridBagConstraints.BOTH;
   gbcMainPanel.weightx = 1;
   gbcMainPanel.weighty = 0;
   gbcMainPanel.anchor = GridBagConstraints.NORTH;
   gbcMainPanel.insets = new Insets( 0,15,0,15 );
   gbMainPanel.setConstraints( tfAlbum, gbcMainPanel );
   pnMainPanel.add( tfAlbum );

   btUploadButton = new JButton( "Upload"  );
   gbcMainPanel.gridx = 6;
   gbcMainPanel.gridy = 19;
   gbcMainPanel.gridwidth = 1;
   gbcMainPanel.gridheight = 1;
   gbcMainPanel.fill = GridBagConstraints.NONE;
   gbcMainPanel.weightx = 1;
   gbcMainPanel.weighty = 0;
   gbcMainPanel.anchor = GridBagConstraints.EAST;
   gbcMainPanel.insets = new Insets( 0,0,0,15 );
   gbMainPanel.setConstraints( btUploadButton, gbcMainPanel );
   pnMainPanel.add( btUploadButton );

   setDefaultCloseOperation( EXIT_ON_CLOSE );

   setContentPane( pnMainPanel );
   pack();
   setVisible( true );
} 
} 
