//======================================================
// Source code generated by jvider v1.8.1 UNREGISTERED version.
// http://www.jvider.com/
//======================================================
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JPanel;
import javax.swing.BorderFactory;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JSplitPane;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JTable;
/**
 * @author  Administrator
 * @created December 2, 2019
 */
public class userview extends JFrame 
{
static userview theuserview;

JPanel pnMainview;
JSplitPane sppSplitPane1;

JPanel pnLeftPanel;

JPanel pnUserActions;
JLabel lbUsernameLabel;

JPanel pnMistPanel;

JPanel pnRightPanel;
JTable tbContentTable;

JPanel pnHead;
/**
 */
public static void main( String args[] ) 
{
   try 
   {
      UIManager.setLookAndFeel("javax.swing.plaf.mac.MacLookAndFeel");
   }
   catch ( ClassNotFoundException e ) 
   {
   }
   catch ( InstantiationException e ) 
   {
   }
   catch ( IllegalAccessException e ) 
   {
   }
   catch ( UnsupportedLookAndFeelException e ) 
   {
   }
   theuserview = new userview();
} 

/**
 */
public userview() 
{
   super( "TITLE" );

   pnMainview = new JPanel();
   GridBagLayout gbMainview = new GridBagLayout();
   GridBagConstraints gbcMainview = new GridBagConstraints();
   pnMainview.setLayout( gbMainview );

   sppSplitPane1 = new JSplitPane( );
   sppSplitPane1.setDividerLocation( 138 );
   sppSplitPane1.setForeground( new Color( 0,0,0 ) );
   sppSplitPane1.setLastDividerLocation( 211 );

   pnLeftPanel = new JPanel();
   GridBagLayout gbLeftPanel = new GridBagLayout();
   GridBagConstraints gbcLeftPanel = new GridBagConstraints();
   pnLeftPanel.setLayout( gbLeftPanel );

   pnUserActions = new JPanel();
   GridBagLayout gbUserActions = new GridBagLayout();
   GridBagConstraints gbcUserActions = new GridBagConstraints();
   pnUserActions.setLayout( gbUserActions );

   lbUsernameLabel = new JLabel( "username"  );
   gbcUserActions.gridx = 0;
   gbcUserActions.gridy = 0;
   gbcUserActions.gridwidth = 1;
   gbcUserActions.gridheight = 1;
   gbcUserActions.fill = GridBagConstraints.NONE;
   gbcUserActions.weightx = 0;
   gbcUserActions.weighty = 0;
   gbcUserActions.anchor = GridBagConstraints.NORTH;
   gbcUserActions.insets = new Insets( 5,0,0,0 );
   gbUserActions.setConstraints( lbUsernameLabel, gbcUserActions );
   pnUserActions.add( lbUsernameLabel );
   gbcLeftPanel.gridx = 0;
   gbcLeftPanel.gridy = 0;
   gbcLeftPanel.gridwidth = 1;
   gbcLeftPanel.gridheight = 1;
   gbcLeftPanel.fill = GridBagConstraints.HORIZONTAL;
   gbcLeftPanel.weightx = 0;
   gbcLeftPanel.weighty = 0;
   gbcLeftPanel.anchor = GridBagConstraints.NORTH;
   gbLeftPanel.setConstraints( pnUserActions, gbcLeftPanel );
   pnLeftPanel.add( pnUserActions );

   pnMistPanel = new JPanel();
   GridBagLayout gbMistPanel = new GridBagLayout();
   GridBagConstraints gbcMistPanel = new GridBagConstraints();
   pnMistPanel.setLayout( gbMistPanel );
   gbcLeftPanel.gridx = 0;
   gbcLeftPanel.gridy = 1;
   gbcLeftPanel.gridwidth = 1;
   gbcLeftPanel.gridheight = 1;
   gbcLeftPanel.fill = GridBagConstraints.BOTH;
   gbcLeftPanel.weightx = 0;
   gbcLeftPanel.weighty = 0;
   gbcLeftPanel.anchor = GridBagConstraints.NORTH;
   gbLeftPanel.setConstraints( pnMistPanel, gbcLeftPanel );
   pnLeftPanel.add( pnMistPanel );
   sppSplitPane1.setLeftComponent(pnLeftPanel);

   pnRightPanel = new JPanel();
   GridBagLayout gbRightPanel = new GridBagLayout();
   GridBagConstraints gbcRightPanel = new GridBagConstraints();
   pnRightPanel.setLayout( gbRightPanel );

   String [][]dataContentTable = new String[][] { new String[] {"musica1", "owner", 
                                                "1:11", "+ ..."}, 
                                                new String[] {"musica2", "owner", 
                                                "1:11", "+ ..."}, 
                                                new String[] {"musica3", "owner", 
                                                "1:11", "+ ..."}, 
                                                new String[] {"musica4", "owner", 
                                                "1:11", "+ ..."}, 
                                                new String[] {"musica5", "owner", 
                                                "1:11", "+ ..."}, 
                                                new String[] {"musica6", "owner", 
                                                "1:11", "+ ..."}, 
                                                new String[] {"musica7", "owner", 
                                                "1:11", "+ ..."} };
   String []colsContentTable = new String[] { "", "", "", "" };
   tbContentTable = new JTable( dataContentTable, colsContentTable );
   tbContentTable.setSelectionBackground( new Color( 212,212,212 ) );
   tbContentTable.setSelectionForeground( new Color( 0,0,0 ) );
   gbcRightPanel.gridx = 0;
   gbcRightPanel.gridy = 1;
   gbcRightPanel.gridwidth = 1;
   gbcRightPanel.gridheight = 1;
   gbcRightPanel.fill = GridBagConstraints.BOTH;
   gbcRightPanel.weightx = 1;
   gbcRightPanel.weighty = 1;
   gbcRightPanel.anchor = GridBagConstraints.CENTER;
   gbRightPanel.setConstraints( tbContentTable, gbcRightPanel );
   pnRightPanel.add( tbContentTable );

   pnHead = new JPanel();
   pnHead.setBorder( BorderFactory.createTitledBorder( "" ) );
   GridBagLayout gbHead = new GridBagLayout();
   GridBagConstraints gbcHead = new GridBagConstraints();
   pnHead.setLayout( gbHead );
   gbcRightPanel.gridx = 0;
   gbcRightPanel.gridy = 0;
   gbcRightPanel.gridwidth = 1;
   gbcRightPanel.gridheight = 1;
   gbcRightPanel.fill = GridBagConstraints.BOTH;
   gbcRightPanel.weightx = 1;
   gbcRightPanel.weighty = 0;
   gbcRightPanel.anchor = GridBagConstraints.NORTH;
   gbRightPanel.setConstraints( pnHead, gbcRightPanel );
   pnRightPanel.add( pnHead );
   sppSplitPane1.setRightComponent(pnRightPanel);
   gbcMainview.gridx = 0;
   gbcMainview.gridy = 0;
   gbcMainview.gridwidth = 37;
   gbcMainview.gridheight = 26;
   gbcMainview.fill = GridBagConstraints.BOTH;
   gbcMainview.weightx = 1;
   gbcMainview.weighty = 1;
   gbcMainview.anchor = GridBagConstraints.CENTER;
   gbMainview.setConstraints( sppSplitPane1, gbcMainview );
   pnMainview.add( sppSplitPane1 );

   setDefaultCloseOperation( EXIT_ON_CLOSE );

   setContentPane( pnMainview );
   pack();
   setVisible( true );
} 
} 
